//
//  block_face.h
//  quark
//
//  Created by Evan Anderson on 11/21/22.
//

#ifndef block_face_h
#define block_face_h

enum BlockFace {
    BLOCK_FACE_DOWN,
    BLOCK_FACE_EAST,
    BLOCK_FACE_EAST_NORTH_EAST,
    BLOCK_FACE_EAST_SOUTH_EAST,
    BLOCK_FACE_NORTH,
    BLOCK_FACE_NORTH_EAST,
    BLOCK_FACE_NORTH_NORTH_EAST,
    BLOCK_FACE_NORTH_NORTH_WEST,
    BLOCK_FACE_NORTH_WEST,
    BLOCK_FACE_SOUTH,
    BLOCK_FACE_SOUTH_EAST,
    BLOCK_FACE_SOUTH_SOUTH_EAST,
    BLOCK_FACE_SOUTH_SOUTH_WEST,
    BLOCK_FACE_SOUTH_WEST,
    BLOCK_FACE_UP,
    BLOCK_FACE_WEST,
    BLOCK_FACE_WEST_NORTH_WEST,
    BLOCK_FACE_WEST_SOUTH_WEST
};

#endif /* block_face_h */
