//
//  potion_effect_type.h
//  quark
//
//  Created by Evan Anderson on 11/3/22.
//

#ifndef potion_effect_type_h
#define potion_effect_type_h

enum PotionEffectType {
    POTION_EFFECT_TYPE_ABSORPTION,
    POTION_EFFECT_TYPE_BAD_OMEN,
    POTION_EFFECT_TYPE_BLINDNESS,
    POTION_EFFECT_TYPE_CONDUIT_POWER,
    POTION_EFFECT_TYPE_CONFUSION,
    POTION_EFFECT_TYPE_DAMAGE_RESISTANCE,
    POTION_EFFECT_TYPE_DARKNESS,
    POTION_EFFECT_TYPE_DOLPHINS_GRACE,
    POTION_EFFECT_TYPE_FAST_DIGGING,
    POTION_EFFECT_TYPE_FIRE_RESISTANCE,
    POTION_EFFECT_TYPE_GLOWING,
    POTION_EFFECT_TYPE_HARM,
    POTION_EFFECT_TYPE_HEAL,
    POTION_EFFECT_TYPE_HEALTH_BOOST,
    POTION_EFFECT_TYPE_HERO_OF_THE_VILLAGE,
    POTION_EFFECT_TYPE_HUNGER,
    POTION_EFFECT_TYPE_INCREASE_DAMAGE,
    POTION_EFFECT_TYPE_INVISIBILITY,
    POTION_EFFECT_TYPE_JUMP,
    POTION_EFFECT_TYPE_LEVITATION,
    POTION_EFFECT_TYPE_LUCK,
    POTION_EFFECT_TYPE_NIGHT_VISION,
    POTION_EFFECT_TYPE_POISON,
    POTION_EFFECT_TYPE_REGENERATION,
    POTION_EFFECT_TYPE_SATURATION,
    POTION_EFFECT_TYPE_SLOW,
    POTION_EFFECT_TYPE_SLOW_DIGGING,
    POTION_EFFECT_TYPE_SLOW_FALLING,
    POTION_EFFECT_TYPE_SPEED,
    POTION_EFFECT_TYPE_UNLUCK,
    POTION_EFFECT_TYPE_WATER_BREATHING,
    POTION_EFFECT_TYPE_WEAKNESS,
    POTION_EFFECT_TYPE_WITHER
};

char *potion_effect_type_get_name(enum PotionEffectType type);
_Bool potion_effect_type_is_instant(enum PotionEffectType type);

#endif /* potion_effect_type_h */
