//
//  potion_effect_type.h
//  quark
//
//  Created by Evan Anderson on 11/3/22.
//

#ifndef potion_effect_type_h
#define potion_effect_type_h

typedef struct PotionEffectType {
    const char *identifier;
} PotionEffectType;

char *potion_effect_type_get_name(PotionEffectType type);
_Bool potion_effect_type_is_instant(PotionEffectType type);

extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_ABSORPTION;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_BAD_OMEN;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_BLINDNESS;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_CONDUIT_POWER;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_CONFUSION;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_DAMAGE_RESISTANCE;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_DARKNESS;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_DOLPHINS_GRACE;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_FIRE_RESISTANCE;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_GLOWING;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_HARM;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_HASTE;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_HEAL;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_HEALTH_BOOST;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_HERO_OF_THE_VILLAGE;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_HUNGER;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_INVISIBILITY;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_JUMP_BOOST;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_LEVITATION;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_LUCK;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_MINING_FATIGUE;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_NIGHT_VISION;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_POISON;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_REGENERATION;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_SATURATION;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_SLOWNESS;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_SLOW_FALLING;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_SPEED;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_STRENGTH;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_UNLUCK;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_WATER_BREATHING;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_WEAKNESS;
extern PotionEffectType POTION_EFFECT_TYPE_MINECRAFT_WITHER;

#endif /* potion_effect_type_h */
