//
//  enchantment.h
//  quark
//
//  Created by Evan Anderson on 11/3/22.
//

#ifndef enchantment_h
#define enchantment_h

enum Enchantment {
    ENCHANTMENT_ARROW_DAMAGE,
    ENCHANTMENT_ARROW_KNOCKBACK,
    ENCHANTMENT_ARROW_FIRE,
    ENCHANTMENT_ARROW_INFINITE,
    ENCHANTMENT_DAMAGE_ALL,
    ENCHANTMENT_DAMAGE_ARTHROPODS,
    ENCHANTMENT_DAMAGE_UNDEAD,
    ENCHANTMENT_DEPTH_STRIDER,
    ENCHANTMENT_DIG_SPEED,
    ENCHANTMENT_DURABILITY,
    ENCHANTMENT_FIRE_ASPECT,
    ENCHANTMENT_KNOCKBACK,
    ENCHANTMENT_LOOT_BONUS_BLOCKS,
    ENCHANTMENT_LOOT_BONUS_MOBS,
    ENCHANTMENT_LUCK,
    ENCHANTMENT_LURE,
    ENCHANTMENT_OXYGEN,
    ENCHANTMENT_PROTECTION_ENVIRONMENTAL,
    ENCHANTMENT_PROTECTION_FIRE,
    ENCHANTMENT_PROTECTION_FALL,
    ENCHANTMENT_PROTECTION_EXPLOSIONS,
    ENCHANTMENT_PROTECTION_PROJECTILE,
    ENCHANTMENT_SILK_TOUCH,
    ENCHANTMENT_THORNS,
    ENCHANTMENT_WATER_WORKER
};

enum EnchantmentTarget {
    ENCHANTMENT_TARGET_ALL,
    ENCHANTMENT_TARGET_ARMOR_FEET,
    ENCHANTMENT_TARGET_ARMOR_HEAD,
    ENCHANTMENT_TARGET_ARMOR_LEGS,
    ENCHANTMENT_TARGET_ARMOR_TORSO,
    ENCHANTMENT_TARGET_BOW,
    ENCHANTMENT_TARGET_CROSSBOW,
    ENCHANTMENT_TARGET_FISHING_ROD,
    ENCHANTMENT_TARGET_TRIDENT,
    ENCHANTMENT_TARGET_WEAPON
};

enum EnchantmentTarget enchantment_get_enchantment_target(enum Enchantment enchantment);

struct Enchant {
    const enum Enchantment type;
    int level;
};

void enchants_destroy(struct Enchant *enchants);

#endif /* enchantment_h */
