//
//  entity_type.h
//  quark
//
//  Created by Evan Anderson on 11/3/22.
//

#ifndef entity_type_h
#define entity_type_h

enum EntityType {
    ENTITY_TYPE_ARMOR_STAND,
    ENTITY_TYPE_ARROW,
    
    ENTITY_TYPE_BEE,
    ENTITY_TYPE_BLAZE,
    ENTITY_TYPE_BOAT,
    
    ENTITY_TYPE_CAT,
    ENTITY_TYPE_CAVE_SPIDER,
    ENTITY_TYPE_CHICKEN,
    ENTITY_TYPE_COD,
    ENTITY_TYPE_COW,
    
    ENTITY_TYPE_DOLPHIN,
    ENTITY_TYPE_DONKEY,
    ENTITY_TYPE_DROPPED_ITEM,
    ENTITY_TYPE_DROWNED,
    
    ENTITY_TYPE_EGG,
    ENTITY_TYPE_ENDER_PEARL,
    ENTITY_TYPE_ENDERMAN,
    
    ENTITY_TYPE_FIREBALL,
    ENTITY_TYPE_FOX,
    
    ENTITY_TYPE_HOGLIN,
    
    ENTITY_TYPE_ILLUSIONER,
    
    ENTITY_TYPE_MINECART,
    ENTITY_TYPE_MINECART_CHEST,
    ENTITY_TYPE_MINECART_COMMAND,
    ENTITY_TYPE_MINECART_FURNACE,
    ENTITY_TYPE_MINECART_TNT,
    ENTITY_TYPE_MULE,
    
    ENTITY_TYPE_OCELOT,
    
    ENTITY_TYPE_PANDA,
    ENTITY_TYPE_PIG,
    ENTITY_TYPE_PIGLIN,
    ENTITY_TYPE_PIGLIN_BRUTE,
    ENTITY_TYPE_PILLAGER,
    ENTITY_TYPE_PLAYER,
    ENTITY_TYPE_PUFFERFISH,
    
    ENTITY_TYPE_RAVAGER,
    
    ENTITY_TYPE_SALMON,
    ENTITY_TYPE_SHEEP,
    ENTITY_TYPE_SILVERFISH,
    ENTITY_TYPE_SKELETON,
    ENTITY_TYPE_SKELETON_HORSE,
    ENTITY_TYPE_SLIME,
    ENTITY_TYPE_SPIDER,
    ENTITY_TYPE_SQUID,
    ENTITY_TYPE_STRIDER,
    
    ENTITY_TYPE_TRIDENT,
    ENTITY_TYPE_TROPICAL_FISH,
    
    ENTITY_TYPE_VEX,
    
    ENTITY_TYPE_WANDERING_TRADER,
    ENTITY_TYPE_WOLF,
    
    ENTITY_TYPE_ZOGLIN,
    ENTITY_TYPE_ZOMBIE,
    ENTITY_TYPE_ZOMBIE_HORSE,
    ENTITY_TYPE_ZOMBIE_VILLAGER
};

int entity_type_get_damage_ticks_maximum(enum EntityType entity_type);
int entity_type_get_fire_ticks_maximum(enum EntityType entity_type);

#endif /* entity_type_h */
