//
//  inventory_type.h
//  quark
//
//  Created by Evan Anderson on 11/3/22.
//

#ifndef inventory_type_h
#define inventory_type_h

enum InventoryType {
    INVENTORY_TYPE_ANVIL,
    INVENTORY_TYPE_BARREL,
    INVENTORY_TYPE_BEACON,
    INVENTORY_TYPE_BLAST_FURNACE,
    INVENTORY_TYPE_BREWING,
    INVENTORY_TYPE_CARTOGRAPHY,
    INVENTORY_TYPE_CHEST,
    INVENTORY_TYPE_CRAFTING,
    INVENTORY_TYPE_CREATIVE,
    INVENTORY_TYPE_DISPENSER,
    INVENTORY_TYPE_DROPPER,
    INVENTORY_TYPE_ENCHANTING,
    INVENTORY_TYPE_ENDER_CHEST,
    INVENTORY_TYPE_FURNACE,
    INVENTORY_TYPE_GRINDSTONE,
    INVENTORY_TYPE_HOPPER,
    INVENTORY_TYPE_LECTERN,
    INVENTORY_TYPE_LOOM,
    INVENTORY_TYPE_MERCHANT,
    INVENTORY_TYPE_PLAYER,
    INVENTORY_TYPE_SHULKER_BOX,
    INVENTORY_TYPE_SMITHING,
    INVENTORY_TYPE_SMOKER,
    INVENTORY_TYPE_STONECUTTER,
    INVENTORY_TYPE_WORKBENCH
};

#endif /* inventory_type_h */
